### ISSUE TITLE
Package Name wild card

### ISSUE THREAD

**Issue by drGarbinsky** [renevanosnabrugge/vsts-promotepackage-task#13]
I'd like to be able to Promote more than one package at a time using wild cards  such as FooPackage* or *Package.

I'm also open to other approaches to solving this if there is another way.

**Comment by renevanosnabrugge** [comment]
Quickest solution is to create a task group with separate tasks and use that.

Verstuurd vanaf mijn iPhone

Op 8 jan. 2019 om 16:45 heeft MicahS <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I'd like to be able to Promote more than one package at a time using wild cards such as FooPackage* or *Package.

I'm also open to other approaches to solving this if there is another way.

**Comment by renevanosnabrugge** [comment]
Will not build this in the task
