### ISSUE TITLE
Not possible to install to AzureDevops 2019 R2

### ISSUE THREAD

**Issue by valerial114** [renevanosnabrugge/vsts-promotepackage-task#15]
Hello,

I tried to install this plugin to AzureDevops 2019 R2. However, installation is disabled. Message "This extension does not support the version of the Server you are currently using. See Works With for supported Server versions.". Could it be resolved? It will be great help with this functionality.

Thank you,

Valeria

**Comment by MarkKharitonov** [comment]
Yes, please.

**Comment by renevanosnabrugge** [comment]
The extension currently only supports the cloud (Azure DevOps Service).

**Comment by renevanosnabrugge** [comment]
Closing for now. If anybody wants to add support (working support) for TFS I am happy to accept
