### ISSUE TITLE
getting http400 bad request

### ISSUE THREAD

**Issue by edufur** [renevanosnabrugge/vsts-promotepackage-task#16]
getting http 400 bad request. there is no information beyond that in the log

**Comment by renevanosnabrugge** [comment]
Fixed in 1.2.10. Accounts running on dev.azure.com were faulty

**Comment by edufur** [comment]
i still get the error. so i dont think it was fixed.

**Comment by renevanosnabrugge** [comment]
Have you tried to remove the task and ADD again? I had trouble with that.

Can you send me if you are using iT in a build or release

Can you send me if you are using azure DevOps url (dev.azure.com<http://dev.azure.com>) or visualstudio ?

When was the account created ? On visualstudio.com<http://visualstudio.com> or dev.azure?

What version do you see in the task ?

Thanks

Verstuurd vanaf mijn iPhone

Op 26 feb. 2019 om 23:55 heeft edufur <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


i still get the error. so i dont think it was fixed.
