### ISSUE TITLE
Promotion of multiple packages in one go

### ISSUE THREAD

**Issue by gegge10** [renevanosnabrugge/vsts-promotepackage-task#18]
We need to promote several npm packages that has the same name format. 

Example:

search-a
search-b
search-c

Is it possible to promote by wildcard for packages with same name format like search-* to promote all packages to another view?

All packages will be in the same version.

**Comment by renevanosnabrugge** [comment]
Thanks for the suggestion. Just as promotion to mulitple views, this is a nice addition. However, quite some work. I am happy to accept Pull request, since I do not have time (on short notice to support this)
