### ISSUE TITLE
Task not available after install on AzureDevOps (cloud)

### ISSUE THREAD

**Issue by daughey** [renevanosnabrugge/vsts-promotepackage-task#20]
I have successfully installed the extension and it shows on the list of installed extensions at the Organisation level.

When I edit a release or build definition the task isn't available to add.  It appears under the list of Marketplace entries but the install button is greyed out.

![promote-release](https://user-images.githubusercontent.com/19322469/54981866-49eb5800-4fa1-11e9-9c78-fc13c53c55a5.png)

This is on the cloud based AzureDevOps (formerly known as VSTS)

**Comment by wgv-srsedate** [comment]
I am also having this issue.  Installed on 3/27 to a cloud instance of ADO.

**Comment by renevanosnabrugge** [comment]
Tried this on multiple clean AzDo accounts, and cannot reproduce. Logging in/Logging out might help sometimes. I saw once that it just did nt show as well, logging in again and CTRL-F5 helped..

**Comment by daughey** [comment]
I've tried it again and it's working now.

Several of us had tried this before and it wasn't working so we know there was a problem (and not just me losing my mind).

We're going to assume it was a Microsoft problem with AzDO and they've now fixed it.

Thank you for checking.

**Comment by wgv-srsedate** [comment]
Yes, verified it's working now.  I also noticed yesterday that it was more than just this task that was having the issue.
