### ISSUE TITLE
 Page not found during universal package promote

### ISSUE THREAD

**Issue by greha** [renevanosnabrugge/vsts-promotepackage-task#24]
I get a "Page not found" error during a universal package promotion.
Attached is the log from the task. I replaced the package / feed guids.

[tasklog_5.log.txt](https://github.com/renevanosnabrugge/vsts-promotepackage-task/files/3247001/tasklog_5.log.txt)

**Comment by brainydevs** [comment]
I can confirm getting the exact same issue on v1.3.1

**Comment by renevanosnabrugge** [comment]
And previous versions?

Verstuurd vanaf mijn iPhone

Op 3 jun. 2019 om 15:45 heeft Brainy Devs <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I can confirm getting the exact same issue on v1.3.1

**Comment by greha** [comment]
Hi,
we started to use it yesterday, so unfortunately I can't comment on any previews versions, and we didn't find a way to specify an older version.

**Comment by brainydevs** [comment]
Version: 1.2.12 was OK for me on 5/29/2019, 9:38:46 AM
Version: 1.3.1 was Failing to promote on 5/30/2019, 12:17:26 PM

**Comment by renevanosnabrugge** [comment]
I’m short on time. Can you revert to older version ?

Verstuurd vanaf mijn iPhone

Op 4 jun. 2019 om 17:09 heeft Brainy Devs <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Version: 1.2.12 was OK for me on 5/29/2019, 9:38:46 AM
Version: 1.3.1 was Failing to promote on 5/30/2019, 12:17:26 PM

**Comment by megel** [comment]
The problem is still there:

![image](https://user-images.githubusercontent.com/15800069/59253683-0d89d880-8c2f-11e9-8be2-127a4f1dfcea.png)

![image](https://user-images.githubusercontent.com/15800069/59253700-15497d00-8c2f-11e9-82fe-32010b3c8a1d.png)

How can I use any previous version?
![image](https://user-images.githubusercontent.com/15800069/59253821-4fb31a00-8c2f-11e9-9c40-4c4a6804c5d1.png)

**Comment by brainydevs** [comment]
Everything is working just fine now (on Version: 1.3.3).
Thanks for reverting back until a fix is provided.

**Comment by renevanosnabrugge** [comment]
Cool thanks for the feedback

Verstuurd vanaf mijn iPhone

Op 11 jun. 2019 om 14:36 heeft Brainy Devs <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Everything is working just fine now (on Version: 1.3.3).
Thanks for reverting back until a fix is provided.

**Comment by megel** [comment]
![image](https://user-images.githubusercontent.com/15800069/59300927-b0267380-8c90-11e9-8b45-3eb5e36c2651.png)
new release works!

**Comment by renevanosnabrugge** [comment]
fixed
