### ISSUE TITLE
Remove hard-coded base URLs for VSTS

### ISSUE THREAD

**Issue by sumo300** [renevanosnabrugge/vsts-promotepackage-task#3]
This task is listed as working for on-premise TFS.  However, looking at the code of the task, the base URLs are hard-coded to VSTS URLs.  Can this task be updated to function for on-premise?

**Comment by renevanosnabrugge** [comment]
I updated the task to only work on VSTS. This was an error on my site. I did not yet have the opportunity to test on TFS. You are welcome to do a pul request and I can provide you with the VSIX to test it locally..

**Comment by renevanosnabrugge** [comment]
hardcoded VSTS urls fixed. On prem not

**Comment by renevanosnabrugge** [comment]
Won't Fix
