### ISSUE TITLE
NuGet packages are not being found in feed with NPM and NuGet

### ISSUE THREAD

**Issue by khdc** [renevanosnabrugge/vsts-promotepackage-task#32]
I'm struggling to get Promote to work. For some reason it cannot find my package.

Our feed has both NPM and NuGet packages. In the task configuration, if I use the drop-down, all I see are NPM packages. I typed in the name of the NuGet package myself, but I get a package not found error.

When its running, the REST calls seem to be only returning NPM packages.

I've attached the diagnostic log.

[package-not-found-log.txt](https://github.com/renevanosnabrugge/vsts-promotepackage-task/files/3633088/package-not-found-log.txt)

I appreciate any help!

**Comment by marshallquick** [comment]
I have the same/similar issue. The dropdowns do not work on my new feed. legacy feeds work fine. 
Please help!

**Comment by renevanosnabrugge** [comment]
Fixed in 
https://github.com/renevanosnabrugge/vsts-promotepackage-task/pull/54
