### ISSUE TITLE
Support PyPi packages

### ISSUE THREAD

**Issue by mikanyg** [renevanosnabrugge/vsts-promotepackage-task#36]
Are there any plans of adding support for PyPi packages? 

Been doing a lot of DevOps in the data analytics space, which is mostly a python environment with some java/scala. Would like to automate the package promotion of PyPi packages and this tasks seems to be what I'm looking for, with the exception that it only supports NuGet and npm.

**Comment by mikanyg** [comment]
Just tried it out (waited for extension request approval) and it works well with Python in our scenario, but we don't need to inspect the package meta data.

Maybe update the docs to state that other feed types than Nuget and npm works, but with limited capabilities?

**Comment by renevanosnabrugge** [comment]
Thanks!

I will update the readme

Verstuurd vanaf mijn iPhone

Op 12 nov. 2019 om 12:10 heeft Mikael Nygaard <notifications@github.com> het volgende geschreven:

﻿

Just tried it out (waited for extension request approval) and it works well with Python in our scenario, but we don't need to inspect the package meta data.

Maybe update the docs to state that other feed types than Nuget and npm works, but with limited capabilities?

**Comment by NightOwl888** [comment]
@mikanyg 

Actually, if you have a chance please make a contribution. 

I added the NuGet/NPM package metadata support and then realized the docs were out of date and the "regular" promotion actually supported more package types than this. I took a look at universal packages and there are no binaries that can be parsed so they cannot be supported in that way. It should be possible and fairly straightforward to support Maven and PyPi packages via metadata, though.

**Comment by mikanyg** [comment]
@NightOwl888 Do you mean adding PyPi package meta data support? 

I would like to if I could, but time and python skills are a constraint currently.
