### ISSUE TITLE
$IsWindows is read-only since PS 6.0

### ISSUE THREAD

**Issue by alex737876** [renevanosnabrugge/vsts-promotepackage-task#49]
Opening vsts-promotepackage-task\vsts-promotepackage-task\vsts-promotepackage-task.ps1 in latest PS VS Code extension gives an error like this:

Starting from PowerShell 6.0, the Variable 'IsWindows' cannot be assigned any more since it is a readonly automatic variable that is built into PowerShell, please use a different name.

Am opening a pull request

**Comment by NightOwl888** [comment]
The reason for this is because `IsWindows` did not exist in earlier versions of Powershell. It is only written to if it is not populated already (indicating it is on a newer version of Powershell that populates it automatically).

**Comment by alex737876** [comment]
Yes, got it. The issue is, that setting it in PS > 6.0 is giving an exception that says 
`Starting from PowerShell 6.0, the Variable 'IsWindows' cannot be assigned any more since it is a readonly automatic variable that is built into PowerShell, please use a different name.`

So i thought would be better not setting it at all :)
See Pull Request #50

**Comment by alex737876** [comment]
@renevanosnabrugge  @NightOwl888  what do you think about that?
