### ISSUE TITLE
How does PAT authentication work with this task?

### ISSUE THREAD

**Issue by armanik11** [renevanosnabrugge/vsts-promotepackage-task#66]
Does the task use the release pipeline's System_AccessToken to call VSTSREST APIs? Or do we need to set some PAT as Environment variable ?

**Comment by jessehouwing** [comment]
It uses the system access token.

**Comment by armanik11** [comment]
Thanks for confirming. 

I took a look at the InitializeRestHeaders method and saw things like **$connectServiceName and $connectedServiceDetails** (not sure what it is) and **$env:PROMOTEPACKAGE_PAT** so wanted to clarify?

function InitializeRestHeaders() {
    $restHeaders = New-Object -TypeName "System.Collections.Generic.Dictionary[[String], [String]]"
    if([string]::IsNullOrWhiteSpace($connectedServiceName)) {
        $patToken = GetAccessToken $connectedServiceDetails
        ValidatePatToken $patToken
        $restHeaders.Add("Authorization", [String]::Concat("Bearer ", $patToken))
    } else {
        Write-Verbose "Username = $Username" -Verbose
        if (![string]::IsNullOrWhiteSpace($env:PROMOTEPACKAGE_PAT)) {
            $Username = ""
            $Password = $env:PROMOTEPACKAGE_PAT
        } else {
            $Username = $connectedServiceDetails.Authorization.Parameters.Username
            $Password = $connectedServiceDetails.Authorization.Parameters.Password
        }
        $alternateCreds = [String]::Concat($Username, ":", $Password)
        $basicAuth = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($alternateCreds))
        $restHeaders.Add("Authorization", [String]::Concat("Basic ", $basicAuth))
    }
    return $restHeaders
}

**Comment by jessehouwing** [comment]
That seems to be some fallback code which is used for local testing. And
you could use it to supply a PAT. But in general the system token should be
present on the agent and this code won't be triggered.

**Comment by armanik11** [comment]
Sounds good. Thanks for the clarification!
