### ISSUE TITLE
##[error]/usr/bin/tar: unrecognized option '--force-local -xvzf'

### ISSUE THREAD

**Issue by packsize-jc** [renevanosnabrugge/vsts-promotepackage-task#67]
Very simple implementation you would think right?

![image](https://user-images.githubusercontent.com/79595344/109034887-542e9900-7685-11eb-9262-33fa3a98a89f.png)

![image](https://user-images.githubusercontent.com/79595344/109034953-64467880-7685-11eb-9918-da82112ba0d9.png)

Thoughts?

**Comment by jessehouwing** [comment]
Your version of tar doesn't support force-local, can you share a few details about your setup?

Agent version:
Operating system:
Operating system version:
Which tar output:
Where tar output:
Tar version:
Tar --help output:

**Comment by packsize-jc** [comment]
This is running in AzureDevops on a current windows VM, I don't have the access necessary to resolve this but I switched it over to Specify Name and version and resolve this another way
